print('Valor 1')
print('Valor 2')
print('Valor 3')
print('Valor 4')
print('Valor 5')
print('Cambio en linea 6')
print('Valor 7')
print('Valor 8')
print('Valor 9')
print('Valor 10')
print('Valor 11')
print('Cambio en linea 12')
print('Valor 13')
print('Valor 14')
print('Valor 15')
print('Valor 16')
print('Valor 17')
print('Cambio en linea 18')
print('Valor 19')
print('Valor 20')
print('Valor 21')
print('Valor 22')
print('Valor 23')
print('Cambio en linea 24')
print('Valor 25')
print('Valor 26')
print('Valor 27')
print('Valor 28')
print('Valor 29')
print('Cambio en linea 30')
print('Valor 31')
print('Valor 32')
print('Valor 33')
print('Valor 34')
print('Valor 35')
print('Cambio en linea 36')
print('Valor 37')
print('Valor 38')
print('Valor 39')
print('Valor 40')
print('Valor 41')
print('Cambio en linea 42')
print('Valor 43')
print('Valor 44')
print('Valor 45')
print('Valor 46')
print('Valor 47')
print('Cambio en linea 48')
print('Valor 49')
print('Valor 50')
print('Valor 51')
print('Valor 52')
print('Valor 53')
print('Cambio en linea 54')
print('Valor 55')
print('Valor 56')
print('Valor 57')
print('Valor 58')
print('Valor 59')
print('Cambio en linea 60')
print('Valor 61')
print('Valor 62')
print('Valor 63')
print('Valor 64')
print('Valor 65')
print('Cambio en linea 66')
print('Valor 67')
print('Valor 68')
print('Valor 69')
print('Valor 70')
print('Valor 71')
print('Cambio en linea 72')
print('Valor 73')
print('Valor 74')
print('Valor 75')
print('Valor 76')
print('Valor 77')
print('Cambio en linea 78')
print('Valor 79')
print('Valor 80')
print('Valor 81')
print('Valor 82')
print('Valor 83')
print('Cambio en linea 84')
print('Valor 85')
print('Valor 86')
print('Valor 87')
print('Valor 88')
print('Valor 89')
print('Cambio en linea 90')
print('Valor 91')
print('Valor 92')
print('Valor 93')
print('Valor 94')
print('Valor 95')
print('Cambio en linea 96')
print('Valor 97')
print('Valor 98')
print('Valor 99')
print('Valor 100')