print('Valor 1')
print('Valor 2')
print('Valor 3')
print('Valor 4')
print('Diferencia en linea 5')
print('Valor 6')
print('Valor 7')
print('Valor 8')
print('Valor 9')
print('Diferencia en linea 10')
print('Valor 11')
print('Valor 12')
print('Valor 13')
print('Valor 14')
print('Diferencia en linea 15')
print('Valor 16')
print('Valor 17')
print('Valor 18')
print('Valor 19')
print('Diferencia en linea 20')
print('Valor 21')
print('Valor 22')
print('Valor 23')
print('Valor 24')
print('Diferencia en linea 25')
print('Valor 26')
print('Valor 27')
print('Valor 28')
print('Valor 29')
print('Diferencia en linea 30')
print('Valor 31')
print('Valor 32')
print('Valor 33')
print('Valor 34')
print('Diferencia en linea 35')
print('Valor 36')
print('Valor 37')
print('Valor 38')
print('Valor 39')
print('Diferencia en linea 40')
print('Valor 41')
print('Valor 42')
print('Valor 43')
print('Valor 44')
print('Diferencia en linea 45')
print('Valor 46')
print('Valor 47')
print('Valor 48')
print('Valor 49')
print('Diferencia en linea 50')
print('Valor 51')
print('Valor 52')
print('Valor 53')
print('Valor 54')
print('Diferencia en linea 55')
print('Valor 56')
print('Valor 57')
print('Valor 58')
print('Valor 59')
print('Diferencia en linea 60')
print('Valor 61')
print('Valor 62')
print('Valor 63')
print('Valor 64')
print('Diferencia en linea 65')
print('Valor 66')
print('Valor 67')
print('Valor 68')
print('Valor 69')
print('Diferencia en linea 70')
print('Valor 71')
print('Valor 72')
print('Valor 73')
print('Valor 74')
print('Diferencia en linea 75')
print('Valor 76')
print('Valor 77')
print('Valor 78')
print('Valor 79')
print('Diferencia en linea 80')
print('Valor 81')
print('Valor 82')
print('Valor 83')
print('Valor 84')
print('Diferencia en linea 85')
print('Valor 86')
print('Valor 87')
print('Valor 88')
print('Valor 89')
print('Diferencia en linea 90')
print('Valor 91')
print('Valor 92')
print('Valor 93')
print('Valor 94')
print('Diferencia en linea 95')
print('Valor 96')
print('Valor 97')
print('Valor 98')
print('Valor 99')
print('Diferencia en linea 100')